spring.application.name=Hostel_Management_System

spring.data.mongodb.uri=${MONGODB_URI}

spring.devtools.restart.enabled=false
management.endpoints.web.exposure.include=health
spring.main.allow-bean-definition-overriding=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}